### ISSUE TITLE
Issues with setup

### ISSUE THREAD

**Issue by RinVindor** [silentjames/WoD-charsheets-for-Obsidian#5]
The sheet seems to have issues when I went through the steps you've listed I'm sure I'm probably doing this wrong so really just hoping to confirm that fact.

![image](https://github.com/user-attachments/assets/718c47f3-4058-4d96-b143-aa75d2509b1c)

**Comment by silentjames** [comment]
Hey @RinVindor!
You'll probably need to add `columnWidth: 680` into your note.
I'm now working on moving some settings (like column width, font, colors, etc) from the css file or a note itself into the FS jsons. Then it will be more beginner-friendly.
